### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by reviewer99** [tommygebru/bui-capstone#8]
### Criteria 1: All Pages are Included
* _Score Level:_ 2
* _Comment(s):_ Individual product pages are missing #5, #6 , #7
 
### Criteria 2: Consistent CSS Styling Across all Pages
* _Score Level:_ 4
* _Comment(s):_ Styling is consistent across all pages.
 
### Criteria 3: Correct Use of CSS Selectors and Syntax
* _Score Level:_ 4
* _Comment(s):_ Uses proper selectors (id, class, element type). All rule sets are valid CSS.
 
### Criteria 4: Use of CSS Grid Element Spacing and Margins
* _Score Level:_ 4
* _Comment(s):_ Sufficient use of grid element spacing and margins.

### Criteria 5: All Pages Updated with Consistent Personality and Branding
* _Score Level:_ 4
* _Comment(s):_ All pages have UI changes. The website uses color, imagery, and fonts to give a sense of personality and branding.

### Criteria 6: Typography Hierarchy
* _Score Level:_ 4
* _Comment(s):_ Pages have a typography hierarchy using fonts, font size, and font color so that the body text and headings text are distinguishable.
 
### Criteria 7: Page Linking
* _Score Level:_ 4
* _Comment(s):_ Links are distinguishable from body text. Navigation from page to page and breadcrumb links functional.

### Criteria 8: Accessibility
* _Score Level:_ 2
* _Comment(s):_ HTML5 tags used but no alt attributes, roles, or aria-labels are used

### Criteria 9 (Optional): Responsive Design
* _Score Level:_ 0
* _Comment(s):_ Page is not responsive
 
### Overall Score: 28/32

Nice job on your capstone project! Overall I liked the design you implemented for the page along with the various hover effects you added. One thing I did notice on chrome was that the page would jump on hover, most likely because the page is adding extra space for the borders being shown on hover.

To expand on your project consider reading about [variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables) and then analyze how you might make use of them on future projects. They are a great tool that allows you to increase the maintainability of your CSS file and it's readability.

**Comment by tommygebru** [comment]
Hey thanks for working on this Reviewer99, your feedback is really great, and I can really understand what I overlooked for this submission.
